# Generated by Django 3.1.4 on 2020-12-22 07:29

from django.db import migrations, models
import issuetracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.IntegerField(default=issuetracker.models.get_unique_number, unique=True),
        ),
    ]
