# Generated by Django 3.1.4 on 2020-12-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0002_auto_20201222_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='issuetracker.department'),
        ),
    ]
