# Generated by Django 3.1.4 on 2021-03-31 06:37

from django.db import migrations, models
import trivia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=trivia.models.generate_unique_id, max_length=6)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=63)),
                ('tags', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=trivia.models.generate_unique_id, max_length=6)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(max_length=63)),
                ('tags', models.CharField(max_length=128)),
            ],
        ),
    ]
