# Generated by Django 3.1.4 on 2021-03-31 12:57

from django.db import migrations, models
import trivia.models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='uid',
            field=models.CharField(default=trivia.models.generate_unique_id, max_length=6, unique=True),
        ),
    ]
