# Generated by Django 3.1.1 on 2020-12-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('source', models.URLField(blank=True, null=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
